### ISSUE TITLE
How do I save registration? (For the website)

### ISSUE THREAD

**Issue by ralphblogz** [ralphblogz/ralphblogz.github.io#1]
Hey guys, I wanted to make a registration for this website, I already know how to make forms, but I still don't know how to save them.

**Comment by vaibhavahuja** [comment]
Hey, form handling can be done by using some server side scripting language like php. 
check out this link to get a basic idea
http://www.c-sharpcorner.com/uploadfile/52bd60/create-an-html-form-and-insert-data-into-database162/

**Comment by ralphblogz** [comment]
Thanks

**Comment by MechRalph04** [comment]
Try hosting a site by urself
